(function(){POLARIS.dialog.add("link",function(c){var q,p=POLARIS.plugins.link,t=function(){var a=this.getDialog(),b=a.getContentElement("target","popupFeatures"),a=a.getContentElement("target","linkTargetName"),f=this.getValue(),b=b.getElement();b.hide();a.setValue("");switch(f){case "frame":a.setLabel(c.lang.link.targetFrameName);a.getElement().show();break;case "popup":b.show();a.setLabel(c.lang.link.targetPopupName);a.getElement().show();break;default:a.setValue(f),a.getElement().hide()}},u=function(){var a=
this.getDialog(),r=["urlOptions","anchorOptions","emailOptions"],f=this.getValue();if("anchor"==f&&(!g||g&&0==g.length))this.setValue(q),alert(b.noAnchorsError);else{q=f;"url"==f?c.config.linkShowTargetTab&&a.showPage("target"):a.hidePage("target");for(var e=0;e<r.length;e++){var d=a.getContentElement("info",r[e]);d&&(d=d.getElement().getParent().getParent(),r[e]==f+"Options"?d.show():d.hide())}a.layout()}},h=function(a){a.target&&this.setValue(a.target[this.id]||"")},m=function(a){a.advanced&&this.setValue(a.advanced[this.id]||
"")},k=function(a){a.target||(a.target={});a.target[this.id]=this.getValue()||""},n=function(a){a.advanced||(a.advanced={});a.advanced[this.id]=this.getValue()||""},l=c.lang.common,b=c.lang.link,g;q="url";var v=!1;c.config.wordprocessor||(v=!0);return{title:b.title,minWidth:264,minHeight:40,resizable:POLARIS.DIALOG_RESIZE_NONE,contents:[{id:"info",label:c.lang.common.generalTab,title:c.lang.common.generalTab,elements:[{type:"fieldset",label:b.type,children:[]},{type:"html",html:""},{id:"linkType",
type:"radio",labelLayout:"vertical",items:v?[[b.toUrl,"url"],[b.toEmail,"email"]]:[[b.toUrl,"url"],[b.toAnchor,"anchor"],[b.toEmail,"email"]],"default":"url",onChange:u,onClick:u,setup:function(a){this.setValue(a.type||"url");this.items.pop(1)},commit:function(a){a.type=this.getValue()}},{type:"vbox",id:"urlOptions",children:[{type:"vbox",children:[{id:"protocol",type:"select",label:l.protocol,width:"100%","default":"http://",items:[["http://‎","http://"],["https://‎","https://"],["ftp://‎","ftp://"],
["news://‎","news://"],[b.other,""]],setup:function(a){a.url&&this.setValue(a.url.protocol||"")},commit:function(a){a.url||(a.url={});a.url.protocol=this.getValue()}},{type:"text",id:"url",label:l.url,required:!0,onLoad:function(){this.allowOnChange=!0},onKeyUp:function(){this.allowOnChange=!1;var a=this.getDialog().getContentElement("info","protocol"),b=this.getValue(),c=/^((javascript:)|[#\/\.\?])/i,e=/^(http|https|ftp|news):\/\/(?=.)/i.exec(b);e?(this.setValue(b.substr(e[0].length)),a.setValue(e[0].toLowerCase())):
c.test(b)&&a.setValue("");this.allowOnChange=!0},onChange:function(){if(this.allowOnChange)this.onKeyUp()},validate:function(){var a=this.getDialog();return a.getContentElement("info","linkType")&&"url"!=a.getValueOf("info","linkType")?!0:!c.config.linkJavaScriptLinksAllowed&&/javascript\:/.test(this.getValue())?(alert(l.invalidValue),!1):this.getDialog().fakeObj?!0:POLARIS.dialog.validate.notEmpty(b.noUrl).apply(this)},setup:function(a){this.allowOnChange=!1;a.url&&this.setValue(a.url.url);this.allowOnChange=
!0},commit:function(a){this.onChange();a.url||(a.url={});a.url.url=this.getValue();this.allowOnChange=!1}},{type:"text",id:"urlText",label:b.urlText,required:!0,setup:function(a){a.url&&this.setValue(a.url.text)},commit:function(a){a.url||(a.url={});a.url.text=this.getValue()}},{type:"text",hidden:!0,id:"urlSubject",label:b.urlSubject,required:!0,setup:function(a){a.url&&this.setValue(a.url.subject)},commit:function(a){a.url||(a.url={});a.url.subject=this.getValue()}}],setup:function(){this.getDialog().getContentElement("info",
"linkType")||this.getElement().show()}}]},{type:"vbox",id:"anchorOptions",children:[{type:"vbox",id:"selectAnchorText",setup:function(){g=p.getEditorAnchors(c);this.getElement()[g&&g.length?"show":"hide"]()},children:[{type:"vbox",id:"selectAnchor",children:[{type:"select",id:"anchorName","default":"",label:b.anchorName,style:"width: 100%;",items:[[""]],setup:function(a){this.clear();if(g)for(var b=0;b<g.length;b++)g[b].name&&this.add(g[b].name);a.anchor&&this.setValue(a.anchor.name);(a=this.getDialog().getContentElement("info",
"linkType"))&&"email"==a.getValue()&&this.focus()},commit:function(a){a.anchor||(a.anchor={});a.anchor.name=this.getValue()},validate:function(){var a=this.getDialog().getContentElement("info","linkType");return a&&"anchor"==a.getValue()&&!this.getValue()?(alert(b.anchor.errorName),!1):!0}}],setup:function(){this.getElement()[g&&g.length?"show":"hide"]()}}]},{type:"html",id:"noAnchors",html:'\x3cdiv role\x3d"note" tabIndex\x3d"-1"\x3e'+POLARIS.tools.htmlEncode(b.noAnchors)+"\x3c/div\x3e",focus:!0,
setup:function(){this.getElement()[g&&g.length?"hide":"show"]()}}],setup:function(){this.getDialog().getContentElement("info","linkType")||this.getElement().hide()}},{type:"vbox",id:"emailOptions",children:[{type:"text",id:"emailAddress",label:b.emailAddress,required:!0,validate:function(){var a=this.getDialog();return a.getContentElement("info","linkType")&&"email"==a.getValueOf("info","linkType")?POLARIS.dialog.validate.notEmpty(b.noEmail).apply(this):!0},setup:function(a){a.email&&this.setValue(a.email.address);
(a=this.getDialog().getContentElement("info","linkType"))&&"email"==a.getValue()&&this.select()},commit:function(a){a.email||(a.email={});a.email.address=this.getValue()}},{type:"text",id:"emailSubject",label:b.emailSubject,setup:function(a){a.email&&this.setValue(a.email.subject)},commit:function(a){a.email||(a.email={});a.email.subject=this.getValue()}},{type:"textarea",id:"emailBody",label:b.emailBody,rows:3,"default":"",setup:function(a){a.email&&this.setValue(a.email.body)},commit:function(a){a.email||
(a.email={});a.email.body=this.getValue()}}],setup:function(){this.getDialog().getContentElement("info","linkType")||this.getElement().hide()}},{type:"html",html:""}]},{id:"advanced",label:c.lang.common.advancedTab,title:c.lang.common.advancedTab,elements:[{type:"vbox",children:[{type:"hbox",widths:["50%","50%"],children:[{type:"text",id:"advId",requiredContent:"a[id]",label:b.id,setup:m,commit:n},{type:"select",id:"advLangDir",requiredContent:"a[dir]",label:c.lang.common.langDir,"default":"",items:[[c.lang.common.notSet,
""],[c.lang.common.langDirLtr,"ltr"],[c.lang.common.langDirRtl,"rtl"]],setup:m,commit:n}]},{type:"text",label:b.name,id:"advName",requiredContent:"a[name]",setup:m,commit:n},{type:"hbox",widths:["50%","50%"],children:[{type:"text",id:"advAccessKey",requiredContent:"a[accesskey]",label:b.acccessKey,maxLength:1,setup:m,commit:n},{type:"text",label:b.tabIndex,id:"advTabIndex",requiredContent:"a[tabindex]",maxLength:5,setup:m,commit:n}]}]},{type:"vbox",children:[{type:"hbox",widths:["50%","50%"],children:[{type:"text",
label:b.advisoryTitle,requiredContent:"a[title]","default":"",id:"advTitle",setup:m,commit:n},{type:"text",label:b.advisoryContentType,requiredContent:"a[type]","default":"",id:"advContentType",setup:m,commit:n}]},{type:"text",label:b.charset,requiredContent:"a[charset]","default":"",id:"advCharset",setup:m,commit:n},{type:"text",label:b.rel,requiredContent:"a[rel]","default":"",id:"advRel",setup:m,commit:n}]}]},{id:"target",hidden:!0,requiredContent:"a[target]",label:b.target,title:b.target,elements:[{type:"select",
id:"linkTargetType",label:l.target,"default":"notSet",style:"width : 100%;",items:[[l.notSet,"notSet"],[b.targetFrame,"frame"],[b.targetPopup,"popup"],[l.targetNew,"_blank"],[l.targetTop,"_top"],[l.targetSelf,"_self"],[l.targetParent,"_parent"]],onChange:t,setup:function(a){a.target&&this.setValue(a.target.type||"notSet");t.call(this)},commit:function(a){a.target||(a.target={});a.target.type=this.getValue()}},{type:"text",id:"linkTargetName",label:b.targetFrameName,"default":"",setup:function(a){a.target&&
this.setValue(a.target.name)},commit:function(a){a.target||(a.target={});a.target.name=this.getValue().replace(/\W/gi,"")}},{type:"vbox",width:"100%",id:"popupFeatures",children:[{type:"hbox",children:[{type:"text",widths:["50%","50%"],label:l.width,id:"width",maxLength:3,validate:POLARIS.dialog.validate.integer(b.validateWidth),setup:h,commit:k},{type:"text",widths:["50%","50%"],label:l.height,validate:POLARIS.dialog.validate.integer(b.validateHeight),id:"height",maxLength:3,setup:h,commit:k}]},
{type:"hbox",children:[{type:"text",widths:["50%","50%"],label:b.popupLeft,id:"left",maxLength:3,validate:POLARIS.dialog.validate.integer(b.validateLeftPosition),setup:h,commit:k},{type:"text",label:b.popupTop,widths:["50%","50%"],id:"top",maxLength:3,validate:POLARIS.dialog.validate.integer(b.validateTopPosition),setup:h,commit:k}]},{type:"vbox",children:[{type:"hbox",children:[{type:"checkbox",id:"resizable",label:b.popupResizable,setup:h,commit:k},{type:"checkbox",id:"status",label:b.popupStatusBar,
setup:h,commit:k}]},{type:"hbox",children:[{type:"checkbox",id:"location",label:b.popupLocationBar,setup:h,commit:k},{type:"checkbox",id:"toolbar",label:b.popupToolbar,setup:h,commit:k}]},{type:"hbox",children:[{type:"checkbox",id:"menubar",label:b.popupMenuBar,setup:h,commit:k},{type:"checkbox",id:"fullscreen",label:b.popupFullScreen,setup:h,commit:k}]},{type:"hbox",children:[{type:"checkbox",id:"scrollbars",label:b.popupScrollBars,setup:h,commit:k},{type:"checkbox",id:"dependent",label:b.popupDependent,
setup:h,commit:k}]}]}]}]}],onShow:function(){var a=this.getParentEditor(),b=a.getSelection(),c=null;(c=p.getSelectedLink(a))&&c.hasAttribute("href")?b.getSelectedElement()||b.selectElement(c):c=null;var e=p.parseLinkAttributes(a,c);this._.selectedElement=c;c||e.url||(b=a.getSelection(),(a=b.getRanges()[0])&&!a.collapsed&&(e.url={protocol:"http://",text:b.getSelectedText()}));this.setupContent(e)},onOk:function(){c.pagination&&c.pagination.adjustCaret(c);var a={};this.commitContent(a);var b=c.getSelection(),
f=p.getLinkAttributes(c,a),e=function(a){if(a){var b=a.getHtml(),b=b.replace(/\u0020\u0020/g," \x26nbsp;");a.setHtml(b)}};if(this._.selectedElement){var d=this._.selectedElement;d.data("polaris-saved-href");d.getHtml();d.setAttributes(f.set);d.removeAttributes(f.removed);"url"!=a.type&&d.removeAttribute("subject");"email"==a.type?(d.setHtml(a.email.address),b.selectElement(d)):"url"==a.type&&(""!=a.url.text&&d.setHtml(a.url.text),b.selectElement(d));d.is("a")&&(e(d),e=new POLARIS.dom.range(c.document),
e.moveToPosition(d,POLARIS.POSITION_AFTER_END),c.focus(),e.select());delete this._.selectedElement}else if(d=b.getRanges()[0],b="",d.collapsed?("email"==a.type?b=a.email.address:"url"==a.type?b=a.url.text||a.url.protocol+a.url.url:"anchor"==a.type&&(b=a.anchor.name),a=new POLARIS.dom.text(b,c.document),d.insertNode(a),d.selectNodeContents(a)):"url"==a.type&&a.url.text&&0<a.url.text.length&&(b=a.url.text,d.deleteContents(),a=new POLARIS.dom.text(b,c.document),d.insertNode(a),d.selectNodeContents(a)),
f=new POLARIS.style({element:"a",attributes:f.set,ignoreReadonly:1}),f.type=POLARIS.STYLE_INLINE,f.applyToRange(d,c),f=d.startContainer&&d.startContainer.getAscendant("a",!0))e(f),e=new POLARIS.dom.range(c.document),e.moveToPosition(f,POLARIS.POSITION_AFTER_END),c.focus(),e.select()},onLoad:function(){c.config.linkShowAdvancedTab||this.hidePage("advanced");c.config.linkShowTargetTab||this.hidePage("target")},onFocus:function(){var a=this.getContentElement("info","linkType");a&&"url"==a.getValue()&&
(a=this.getContentElement("info","url"),a.select())}}})})();