(function(){function k(a,k,m){var r=q[this.id];if(r)for(var n=this instanceof POLARIS.ui.dialog.checkbox,b=0;b<r.length;b++){var d=r[b];switch(d.type){case 1:if(!a)continue;if(null!==a.getAttribute(d.name)){a=a.getAttribute(d.name);n?this.setValue("true"==a.toLowerCase()):this.setValue(a);return}n&&this.setValue(!!d["default"]);break;case 2:if(!a)continue;if(d.name in m){a=m[d.name];n?this.setValue("true"==a.toLowerCase()):this.setValue(a);return}n&&this.setValue(!!d["default"]);break;case 4:if(!k)continue;
if(k.getAttribute(d.name)){a=k.getAttribute(d.name);n?this.setValue("true"==a.toLowerCase()):this.setValue(a);return}n&&this.setValue(!!d["default"])}}}function m(a,k,m){var r=q[this.id];if(r)for(var n=""===this.getValue(),b=this instanceof POLARIS.ui.dialog.checkbox,d=0;d<r.length;d++){var c=r[d];switch(c.type){case 1:if(!a||"data"==c.name&&k&&!a.hasAttribute("data"))continue;var f=this.getValue();n||b&&f===c["default"]?a.removeAttribute(c.name):a.setAttribute(c.name,f);break;case 2:if(!a)continue;
f=this.getValue();if(n||b&&f===c["default"])c.name in m&&m[c.name].remove();else if(c.name in m)m[c.name].setAttribute("value",f);else{var g=POLARIS.dom.element.createFromHtml("\x3cpolaris:param\x3e\x3c/polaris:param\x3e",a.getDocument());g.setAttributes({name:c.name,value:f});1>a.getChildCount()?g.appendTo(a):g.insertBefore(a.getFirst())}break;case 4:if(!k)continue;f=this.getValue();n||b&&f===c["default"]?k.removeAttribute(c.name):k.setAttribute(c.name,f)}}}function u(a){if(a=v.exec(a))return a[2]}
for(var q={id:[{type:1,name:"id"}],classid:[{type:1,name:"classid"}],codebase:[{type:1,name:"codebase"}],pluginspage:[{type:4,name:"pluginspage"}],src:[{type:2,name:"movie"},{type:4,name:"src"},{type:1,name:"data"}],name:[{type:4,name:"name"}],align:[{type:1,name:"align"}],"class":[{type:1,name:"class"},{type:4,name:"class"}],width:[{type:1,name:"width"},{type:4,name:"width"}],height:[{type:1,name:"height"},{type:4,name:"height"}],hSpace:[{type:1,name:"hSpace"},{type:4,name:"hSpace"}],vSpace:[{type:1,
name:"vSpace"},{type:4,name:"vSpace"}],style:[{type:1,name:"style"},{type:4,name:"style"}],type:[{type:4,name:"type"}]},t="play loop menu quality scale salign wmode bgcolor base flashvars allowScriptAccess allowFullScreen".split(" "),p=0;p<t.length;p++)q[t[p]]=[{type:4,name:t[p]},{type:2,name:t[p]}];t=["play","loop","menu"];for(p=0;p<t.length;p++)q[t[p]][0]["default"]=q[t[p]][1]["default"]=!0;var v=/^(\d+(?:\.\d+)?)(px|%)$/;POLARIS.dialog.add("flash",function(a){var p=!a.config.flashEmbedTagOnly,
t=a.config.flashAddEmbedTag||a.config.flashEmbedTagOnly,r,n="\x3cdiv\x3e"+POLARIS.tools.htmlEncode(a.lang.common.preview)+'\x3cbr\x3e\x3cdiv id\x3d"polaris_FlashPreviewLoader'+POLARIS.tools.getNextNumber()+'" style\x3d"display:none"\x3e\x3cdiv class\x3d"loading"\x3e\x26nbsp;\x3c/div\x3e\x3c/div\x3e\x3cdiv id\x3d"polaris_FlashPreviewBox'+POLARIS.tools.getNextNumber()+'" class\x3d"FlashPreviewBox"\x3e\x3c/div\x3e\x3c/div\x3e';return{title:a.lang.flash.title,minWidth:244,minHeight:180,resizable:POLARIS.DIALOG_RESIZE_NONE,
onShow:function(){this.fakeImage=this.objectNode=this.embedNode=null;r=new POLARIS.dom.element("embed",a.document);var b=this.getSelectedElement();if(b&&b.data("polaris-real-element-type")&&"flash"==b.data("polaris-real-element-type")){this.fakeImage=b;var d=a.restoreRealElement(b),c=null,f=null,g={};if("polaris:object"==d.getName()){c=d;d=c.getElementsByTag("embed","polaris");0<d.count()&&(f=d.getItem(0));for(var d=c.getElementsByTag("param","polaris"),e=0,k=d.count();e<k;e++){var l=d.getItem(e),
h=l.getAttribute("name"),l=l.getAttribute("value");g[h]=l}}else"polaris:embed"==d.getName()&&(f=d);this.objectNode=c;this.embedNode=f;this.setupContent(c,f,g,b)}},onOk:function(){var b=null,d=null,c=null;this.fakeImage?(b=this.objectNode,d=this.embedNode):(p&&(b=POLARIS.dom.element.createFromHtml("\x3cpolaris:object\x3e\x3c/polaris:object\x3e",a.document)),t&&(d=POLARIS.dom.element.createFromHtml("\x3cpolaris:embed\x3e\x3c/polaris:embed\x3e",a.document),d.setAttributes({type:"application/x-shockwave-flash",
pluginspage:"http://www.macromedia.com/go/getflashplayer"}),b&&d.appendTo(b)));if(b)for(var c={},f=b.getElementsByTag("param","polaris"),g=0,e=f.count();g<e;g++)c[f.getItem(g).getAttribute("name")]=f.getItem(g);f={};g={};this.commitContent(b,d,c,f,g);b=a.createFakeElement(b||d,"polaris_flash","flash",!0);b.setAttributes(g);b.setStyles(f);this.fakeImage?(b.replace(this.fakeImage),a.getSelection().selectElement(b)):a.insertElement(b)},onHide:function(){a.execCommand("clearFilePicker");this.preview&&
this.preview.setHtml("")},contents:[{id:"info",label:a.lang.common.generalTab,accessKey:"I",elements:[{type:"vbox",padding:0,children:[{type:"hbox",align:"right",children:[{id:"src",type:"text",label:a.lang.common.url,style:"width:172px",required:!0,validate:POLARIS.dialog.validate.notEmpty(a.lang.flash.validateSrc),setup:k,commit:m,onLoad:function(){var b=this.getDialog(),a=function(a){r.setAttribute("src",a);b.preview.setHtml('\x3cembed height\x3d"100%" width\x3d"100%" src\x3d"'+POLARIS.tools.htmlEncode(r.getAttribute("src"))+
'" type\x3d"application/x-shockwave-flash"\x3e\x3c/embed\x3e')};b.preview=b.getContentElement("advanced","preview").getElement().getChild(3);this.on("change",function(b){b.data&&b.data.value&&a(b.data.value)});this.getInputElement().on("change",function(){a(this.getValue())},this)}},{type:"vbox",filebrowser:"uploadButton",label:a.lang.image.upload,style:"width:66px",children:[{type:"file",id:"upload",style:"width:100%",hidden:!0,label:a.lang.image.btnUpload,size:38},{type:"fileButton",id:"uploadButton",
style:"width:100%",filebrowser:"info:src",label:a.lang.image.btnUpload,"for":["info","upload"]}]}]}]},{type:"hbox",children:[{type:"hbox",children:[{type:"text",id:"width",maxLength:3,width:"58px",requiredContent:"embed[width]",label:a.lang.common.width,validate:function(){var b=this.getValue(),d=!!POLARIS.dialog.validate.integer()(b);if(d){var b=parseInt(b,10),c=this.getDialog().getValueOf("info","widthType"),d=!0;isNaN(b)||("%"==c?(d=!!(0<b&&100>=b))||alert(a.lang.flash.invalidWidth.replace("%1",
"100"+c)):(d=!!(0<b&&512>=b))||alert(a.lang.flash.invalidWidth.replace("%1","512"+c)))}else alert(a.lang.common.invalidWidth);return d},setup:function(b,a,c){var f=q[this.id];if(f)for(var g=0;g<f.length;g++){var e=f[g];switch(e.type){case 1:if(!b)continue;if(null!==b.getAttribute(e.name)){b=parseInt(b.getAttribute(e.name),10);isNaN(b)||this.setValue(b);return}break;case 2:if(!b)continue;if(e.name in c){b=parseInt(c[e.name],10);isNaN(b)||this.setValue(b);return}break;case 4:if(!a)continue;if(a.getAttribute(e.name)){b=
parseInt(a.getAttribute(e.name),10);isNaN(b)||this.setValue(b);return}}}},commit:function(b,a,c){var f=q[this.id];if(f)for(var g=""===this.getValue(),e=this instanceof POLARIS.ui.dialog.checkbox,k=0;k<f.length;k++){var l=f[k];switch(l.type){case 1:if(!b||"data"==l.name&&a&&!b.hasAttribute("data"))continue;var h=this.getValue();if(g||e&&h===l["default"])b.removeAttribute(l.name);else{var h=parseInt(h,10),m=this.getDialog().getValueOf("info","widthType");b.setAttribute(l.name,h+m)}break;case 2:if(!b)continue;
h=this.getValue();if(g||e&&h===l["default"])l.name in c&&c[l.name].remove();else if(l.name in c)h=parseInt(h,10),m=this.getDialog().getValueOf("info","widthType"),c[l.name].setAttribute("value",h+m);else{var n=POLARIS.dom.element.createFromHtml("\x3cpolaris:param\x3e\x3c/polaris:param\x3e",b.getDocument()),h=parseInt(h,10),m=this.getDialog().getValueOf("info","widthType");n.setAttributes({name:l.name,value:h+m});1>b.getChildCount()?n.appendTo(b):n.insertBefore(b.getFirst())}break;case 4:if(!a)continue;
h=this.getValue();g||e&&h===l["default"]?a.removeAttribute(l.name):(h=parseInt(h,10),m=this.getDialog().getValueOf("info","widthType"),a.setAttribute(l.name,h+m))}}}},{type:"select",id:"widthType",width:"58px",label:a.lang.common.widthUnit,labelStyle:"visibility:hidden","default":"px",items:[[a.lang.common.unitPx,"px"],[a.lang.common.unitPc,"%"]],setup:function(b,a,c){var f=q.width;if(f)for(var g=0;g<f.length;g++){var e=f[g];switch(e.type){case 1:if(!b)continue;if(null!==b.getAttribute(e.name)){b=
u(b.getAttribute(e.name));this.setValue(b||"px");return}break;case 2:if(!b)continue;if(e.name in c){b=u(c[e.name]);this.setValue(b||"px");return}break;case 4:if(!a)continue;if(a.getAttribute(e.name)){b=u(a.getAttribute(e.name));this.setValue(b||"px");return}}}}}]},{type:"hbox",children:[{type:"text",id:"height",width:"58px",maxLength:3,requiredContent:"embed[height]",label:a.lang.common.height,validate:function(){var b=this.getValue(),d=!!POLARIS.dialog.validate.integer()(b);if(d){var b=parseInt(b,
10),c=this.getDialog().getValueOf("info","heightType"),d=!0;isNaN(b)||("%"==c?(d=!!(0<b&&100>=b))||alert(a.lang.flash.invalidHeight.replace("%1","100"+c)):(d=!!(0<b&&512>=b))||alert(a.lang.flash.invalidHeight.replace("%1","512"+c)))}else alert(a.lang.common.invalidHeight);return d},setup:function(b,a,c){var f=q[this.id];if(f)for(var g=0;g<f.length;g++){var e=f[g];switch(e.type){case 1:if(!b)continue;if(null!==b.getAttribute(e.name)){b=parseInt(b.getAttribute(e.name),10);isNaN(b)||this.setValue(b);
return}break;case 2:if(!b)continue;if(e.name in c){b=parseInt(c[e.name],10);isNaN(b)||this.setValue(b);return}break;case 4:if(!a)continue;if(a.getAttribute(e.name)){b=parseInt(a.getAttribute(e.name),10);isNaN(b)||this.setValue(b);return}}}},commit:function(b,a,c){var f=q[this.id];if(f)for(var g=""===this.getValue(),e=this instanceof POLARIS.ui.dialog.checkbox,m=0;m<f.length;m++){var l=f[m];switch(l.type){case 1:if(!b||"data"==l.name&&a&&!b.hasAttribute("data"))continue;var h=this.getValue();if(g||
e&&h===l["default"])b.removeAttribute(l.name);else{var h=parseInt(h,10),k=this.getDialog().getValueOf("info","heightType");b.setAttribute(l.name,h+k)}break;case 2:if(!b)continue;h=this.getValue();if(g||e&&h===l["default"])l.name in c&&c[l.name].remove();else if(l.name in c)h=parseInt(h,10),k=this.getDialog().getValueOf("info","heightType"),c[l.name].setAttribute("value",h+k);else{var n=POLARIS.dom.element.createFromHtml("\x3cpolaris:param\x3e\x3c/polaris:param\x3e",b.getDocument()),h=parseInt(h,10),
k=this.getDialog().getValueOf("info","heightType");n.setAttributes({name:l.name,value:h+k});1>b.getChildCount()?n.appendTo(b):n.insertBefore(b.getFirst())}break;case 4:if(!a)continue;h=this.getValue();g||e&&h===l["default"]?a.removeAttribute(l.name):(h=parseInt(h,10),k=this.getDialog().getValueOf("info","heightType"),a.setAttribute(l.name,h+k))}}}},{type:"select",id:"heightType",width:"58px",label:a.lang.common.heightUnit,labelStyle:"visibility:hidden","default":"px",items:[[a.lang.common.unitPx,
"px"],[a.lang.common.unitPc,"%"]],setup:function(a,d,c){var f=q.height;if(f)for(var g=0;g<f.length;g++){var e=f[g];switch(e.type){case 1:if(!a)continue;if(null!==a.getAttribute(e.name)){a=u(a.getAttribute(e.name));this.setValue(a||"px");return}break;case 2:if(!a)continue;if(e.name in c){a=u(c[e.name]);this.setValue(a||"px");return}break;case 4:if(!d)continue;if(d.getAttribute(e.name)){a=u(d.getAttribute(e.name));this.setValue(a||"px");return}}}}}]}]},{type:"hbox",children:[{type:"text",id:"hSpace",
style:"width:78px;",requiredContent:"embed[hspace]",label:a.lang.flash.hSpace,maxLength:3,validate:POLARIS.dialog.validate.integer(a.lang.flash.validateHSpace),setup:k,commit:m},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:a.lang.common.unitPx}]},{type:"text",id:"vSpace",style:"width:78px;",requiredContent:"embed[vspace]",label:a.lang.flash.vSpace,maxLength:3,validate:POLARIS.dialog.validate.integer(a.lang.flash.validateVSpace),setup:k,commit:m},{type:"vbox",children:[{type:"html",
html:"\x26nbsp;"},{type:"html",html:a.lang.common.unitPx}]}]},{type:"hbox",widths:["50%","50%"],children:[{id:"scale",type:"select",requiredContent:"embed[scale]",label:a.lang.flash.scale,"default":"",style:"width : 100%;",items:[[a.lang.common.notSet,""],[a.lang.flash.scaleAll,"showall"],[a.lang.flash.scaleNoBorder,"noborder"],[a.lang.flash.scaleFit,"exactfit"]],setup:k,commit:m},{id:"allowScriptAccess",type:"select",requiredContent:"embed[allowscriptaccess]",label:a.lang.flash.access,"default":"",
style:"width : 100%;",items:[[a.lang.common.notSet,""],[a.lang.flash.accessAlways,"always"],[a.lang.flash.accessSameDomain,"samedomain"],[a.lang.flash.accessNever,"never"]],setup:k,commit:m}]},{type:"hbox",widths:["50%","50%"],children:[{id:"wmode",type:"select",requiredContent:"embed[wmode]",label:a.lang.flash.windowMode,"default":"",style:"width : 100%;",items:[[a.lang.common.notSet,""],[a.lang.flash.windowModeWindow,"window"],[a.lang.flash.windowModeOpaque,"opaque"],[a.lang.flash.windowModeTransparent,
"transparent"]],setup:k,commit:m},{id:"quality",type:"select",requiredContent:"embed[quality]",label:a.lang.flash.quality,"default":"high",style:"width : 100%;",items:[[a.lang.common.notSet,""],[a.lang.flash.qualityBest,"best"],[a.lang.flash.qualityHigh,"high"],[a.lang.flash.qualityAutoHigh,"autohigh"],[a.lang.flash.qualityMedium,"medium"],[a.lang.flash.qualityAutoLow,"autolow"],[a.lang.flash.qualityLow,"low"]],setup:k,commit:m}]},{type:"hbox",widths:["50%","50%"],children:[{id:"align",type:"select",
requiredContent:"object[align]",label:a.lang.common.align,"default":"",style:"width : 100%;",items:[[a.lang.common.notSet,""],[a.lang.common.alignLeft,"left"],[a.lang.common.alignBottom,"bottom"],[a.lang.common.alignMiddle,"middle"],[a.lang.common.alignRight,"right"],[a.lang.common.alignTop,"top"]],setup:k,commit:function(a,d,c,f,g){var e=this.getValue();m.apply(this,arguments);e&&(g.align=e)}},{type:"html",html:"\x3cdiv\x3e\x3c/div\x3e"}]},{type:"vbox",children:[{type:"hbox",widths:["50%","50%"],
children:[{type:"checkbox",id:"menu",label:a.lang.flash.chkMenu,style:"padding-left: 10px;","default":!0,setup:k,commit:m},{type:"checkbox",id:"play",label:a.lang.flash.chkPlay,style:"padding-left: 10px;","default":!0,setup:k,commit:m}]},{type:"hbox",widths:["50%","50%"],children:[{type:"checkbox",id:"loop",label:a.lang.flash.chkLoop,style:"padding-left: 10px;","default":!0,setup:k,commit:m},{type:"html",html:"\x26nbsp;"}]}]}]},{id:"advanced",label:a.lang.common.advancedTab,elements:[{type:"text",
id:"id",requiredContent:"object[id]",label:a.lang.common.id,setup:k,commit:m},{type:"text",id:"bgcolor",requiredContent:"embed[bgcolor]",label:a.lang.flash.bgcolor,setup:k,commit:m},{type:"vbox",children:[{type:"html",id:"preview",html:n}]}]}]}})})();