(function(){POLARIS.dialog.add("headerfooter",function(g){var d=g.lang.pagination,h=function(b){b=b.data.getTarget();if("a"!==b.getName()&&(b=b.getAscendant("a"),!b))return;this._.dialog.headerFooterIndex=parseInt(b.getAttribute("header-footer-index"));b=b.getAttribute("aria-labelledby");for(var c=this.getElement().getElementsByTag("a"),a=0;a<c.$.length;a++){var d=c.getItem(a),e=d.getAttribute("aria-labelledby");d.$.className=b===e?"polaris_list_item_selected":"polaris_list_item"}},l=POLARIS.tools.addFunction(function(b,
c){b=new POLARIS.dom.event(b);c=new POLARIS.dom.element(c);var a;a=b.getKeystroke();var d="rtl"==g.lang.dir;switch(a){case 38:if(a=c.getParent().getParent().getPrevious())a=a.getChild([c.getParent().getIndex(),0]),a.focus();b.preventDefault();break;case 40:(a=c.getParent().getParent().getNext())&&(a=a.getChild([c.getParent().getIndex(),0]))&&a.focus();b.preventDefault();break;case 32:h({data:b});b.preventDefault();break;case d?37:39:if(a=c.getParent().getNext())a=a.getChild(0),a.focus(),b.preventDefault(!0);
else if(a=c.getParent().getParent().getNext())(a=a.getChild([0,0]))&&a.focus(),b.preventDefault(!0);break;case d?39:37:if(a=c.getParent().getPrevious())a=a.getChild(0),a.focus(),b.preventDefault(!0);else if(a=c.getParent().getParent().getPrevious())a=a.getLast().getChild(0),a.focus(),b.preventDefault(!0)}}),e=POLARIS.tools.getNextId()+"_headerfooter_label",e=['\x3cdiv class\x3d"header_footer_format_list_div"\x3e\x3cspan id\x3d"'+e+'" class\x3d"polaris_voice_label"\x3e'+d.headerfooter+"\x3c/span\x3e",
'\x3ctable align\x3d"left" role\x3d"listbox" aria-labelledby\x3d"'+e+'" style\x3d"table-layout: fixed; border-collapse: collapse; border-spacing: 0;" cellpadding\x3d"1"',POLARIS.env.ie&&POLARIS.env.quirks?' style\x3d"position:absolute;"':"","\x3e\x3ctbody\x3e"],k=0,f=function(b,c){var a=POLARIS.tools.getNextNumber();b.push('\x3ctr role\x3d"presentation"\x3e\x3ctd class\x3d"header_footer_format_list_td" style\x3d"vertical-align: center;" role\x3d"presentation"\x3e\x3ca href\x3d"javascript:void(0)" role\x3d"option"',
' aria-labelledby\x3d"'+a+'"',' class\x3d"polaris_list_item polaris_hand" tabindex\x3d"-1" onkeydown\x3d"POLARIS.tools.callFunction( ',l,', event, this );" header-footer-index\x3d"'+k+'"\x3e','\x3cspan id\x3d"'+a+'"\x3e'+c+"\x3c/span\x3e\x3c/a\x3e","\x3c/td\x3e\x3c/tr\x3e");k++};f(e,"\x3cdiv\x3e"+d.headerAndFooter.empty+"\x3c/div\x3e");f(e,'\x3cdiv style\x3d"text-align:left;"\x3e'+d.pageNumberStyle.left+"\x3c/div\x3e");f(e,'\x3cdiv style\x3d"text-align:center;"\x3e'+d.pageNumberStyle.center+"\x3c/div\x3e");
f(e,'\x3cdiv style\x3d"text-align:right;"\x3e'+d.pageNumberStyle.right+"\x3c/div\x3e");f(e,'\x3cdiv style\x3d"border-bottom:1px solid #000000;text-align:left;"\x3e'+d.pageNumberStyle.left+"\x3c/div\x3e");f(e,'\x3cdiv style\x3d"border-bottom:1px solid #000000;text-align:center;"\x3e'+d.pageNumberStyle.center+"\x3c/div\x3e");f(e,'\x3cdiv style\x3d"border-bottom:1px solid #000000;text-align:right;"\x3e'+d.pageNumberStyle.right+"\x3c/div\x3e");f(e,'\x3cdiv style\x3d"background-color:#d2d2d2;text-align:left;"\x3e'+
d.pageNumberStyle.left+"\x3c/div\x3e");f(e,'\x3cdiv style\x3d"background-color:#d2d2d2;text-align:center;"\x3e'+d.pageNumberStyle.center+"\x3c/div\x3e");f(e,'\x3cdiv style\x3d"background-color:#d2d2d2;text-align:right;"\x3e'+d.pageNumberStyle.right+"\x3c/div\x3e");e.push("\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e");return{title:d.headerfooter,minWidth:214,minHeight:36,resizable:POLARIS.DIALOG_RESIZE_NONE,contents:[{id:"info",expand:!0,label:g.lang.common.generalTab,elements:[{type:"fieldset",label:d.headerAndFooter.type,
children:[]},{type:"html",html:""},{type:"radio",label:"",id:"radioHeaderFooterType","default":"header",items:[[d.headerAndFooter.header,"header"],[d.headerAndFooter.footer,"footer"]]},{type:"html",html:""},{type:"fieldset",label:d.headerAndFooter.pos,children:[]},{type:"html",html:""},{type:"radio",label:"",id:"radioHeaderFooterPos","default":"both",items:[[d.headerAndFooter.display.both,"both"],[d.headerAndFooter.display.odd,"odd"],[d.headerAndFooter.display.even,"even"]]},{type:"html",html:""},
{type:"html",id:"headerFooterStyle",html:e.join(""),onClick:h,style:"border-collapse: separate; overflow:auto;"}]}],onLoad:function(){},onShow:function(){},onOk:function(){function b(a){return'\x3cp width\x3d"100%"'+(a?' style\x3d"'+a+'"':"")+'\x3e\x3cspan doc-data-role\x3d"page-number"\x3e\x26#8203;\x3c/span\x3e\x3c/p\x3e'}var c={type:this.getContentElement("info","radioHeaderFooterType").getValue(),position:this.getContentElement("info","radioHeaderFooterPos").getValue(),innerHtml:""};switch(this.headerFooterIndex){case 0:c.innerHtml=
"";c.showHeaderFooter=!0;break;case 1:c.innerHtml=b("text-align:left;");break;case 2:c.innerHtml=b("text-align:center;");break;case 3:c.innerHtml=b("text-align:right;");break;case 4:c.innerHtml=b("border-bottom:1px solid #000000; text-align:left;");break;case 5:c.innerHtml=b("border-bottom:1px solid #000000; text-align:center;");break;case 6:c.innerHtml=b("border-bottom:1px solid #000000; text-align:right;");break;case 7:c.innerHtml=b("background-color:#d2d2d2;text-align:left;");break;case 8:c.innerHtml=
b("background-color:#d2d2d2;text-align:center;");break;case 9:c.innerHtml=b("background-color:#d2d2d2;text-align:right;")}g.fire("setHeaderFooter",c)}}})})();