(function(){POLARIS.dialog.add("pagenumber",function(n){var e=n.lang.pagination,f=function(){var a=this.getDialog();a.getContentElement("info","radioOptionNone")!=this&&a.getContentElement("info","radioOptionNone").setValue("");a.getContentElement("info","radioOptionBothTop")!=this&&a.getContentElement("info","radioOptionBothTop").setValue("");a.getContentElement("info","radioOptionBothBottom")!=this&&a.getContentElement("info","radioOptionBothBottom").setValue("");a.getContentElement("info","radioOptionInsideTop")!=
this&&a.getContentElement("info","radioOptionInsideTop").setValue("");a.getContentElement("info","radioOptionInsideBottom")!=this&&a.getContentElement("info","radioOptionInsideBottom").setValue("");a.getContentElement("info","radioOptionOutsideTop")!=this&&a.getContentElement("info","radioOptionOutsideTop").setValue("");a.getContentElement("info","radioOptionOutsideBottom")!=this&&a.getContentElement("info","radioOptionOutsideBottom").setValue("");a=this.getValue();m(a);this._.dialog.pageNumberRadioSelected=
a},m=function(a){"0"==a?(POLARIS.document.getById(c).setStyle("display","none"),POLARIS.document.getById(d).setStyle("display","none"),POLARIS.document.getById(b).setStyle("display","none")):"1"==a?(a=POLARIS.document.getById(g),a.setStyle("text-align","left"),a.setStyle("vertical-align","top"),POLARIS.document.getById(c).removeStyle("display"),POLARIS.document.getById(d).setStyle("display","none"),POLARIS.document.getById(b).setStyle("display","none")):"2"==a?(a=POLARIS.document.getById(g),a.setStyle("text-align",
"center"),a.setStyle("vertical-align","top"),POLARIS.document.getById(c).removeStyle("display"),POLARIS.document.getById(d).setStyle("display","none"),POLARIS.document.getById(b).setStyle("display","none")):"3"==a?(a=POLARIS.document.getById(g),a.setStyle("text-align","right"),a.setStyle("vertical-align","top"),POLARIS.document.getById(c).removeStyle("display"),POLARIS.document.getById(d).setStyle("display","none"),POLARIS.document.getById(b).setStyle("display","none")):"4"==a?(a=POLARIS.document.getById(g),
a.setStyle("text-align","left"),a.setStyle("vertical-align","bottom"),POLARIS.document.getById(c).removeStyle("display"),POLARIS.document.getById(d).setStyle("display","none"),POLARIS.document.getById(b).setStyle("display","none")):"5"==a?(a=POLARIS.document.getById(g),a.setStyle("text-align","center"),a.setStyle("vertical-align","bottom"),POLARIS.document.getById(c).removeStyle("display"),POLARIS.document.getById(d).setStyle("display","none"),POLARIS.document.getById(b).setStyle("display","none")):
"6"==a?(a=POLARIS.document.getById(g),a.setStyle("text-align","right"),a.setStyle("vertical-align","bottom"),POLARIS.document.getById(c).removeStyle("display"),POLARIS.document.getById(d).setStyle("display","none"),POLARIS.document.getById(b).setStyle("display","none")):"7"==a?(a=POLARIS.document.getById(k),a.setStyle("text-align","right"),a.setStyle("vertical-align","top"),a=POLARIS.document.getById(l),a.setStyle("text-align","left"),a.setStyle("vertical-align","top"),POLARIS.document.getById(d).removeStyle("display"),
POLARIS.document.getById(b).removeStyle("display"),POLARIS.document.getById(c).setStyle("display","none")):"8"==a?(a=POLARIS.document.getById(k),a.setStyle("text-align","right"),a.setStyle("vertical-align","bottom"),a=POLARIS.document.getById(l),a.setStyle("text-align","left"),a.setStyle("vertical-align","bottom"),POLARIS.document.getById(d).removeStyle("display"),POLARIS.document.getById(b).removeStyle("display"),POLARIS.document.getById(c).setStyle("display","none")):"9"==a?(a=POLARIS.document.getById(k),
a.setStyle("text-align","left"),a.setStyle("vertical-align","top"),a=POLARIS.document.getById(l),a.setStyle("text-align","right"),a.setStyle("vertical-align","top"),POLARIS.document.getById(d).removeStyle("display"),POLARIS.document.getById(b).removeStyle("display"),POLARIS.document.getById(c).setStyle("display","none"),POLARIS.document.getById(d).removeStyle("display"),POLARIS.document.getById(b).removeStyle("display"),POLARIS.document.getById(c).setStyle("display","none")):"10"==a&&(a=POLARIS.document.getById(k),
a.setStyle("text-align","left"),a.setStyle("vertical-align","bottom"),a=POLARIS.document.getById(l),a.setStyle("text-align","right"),a.setStyle("vertical-align","bottom"),POLARIS.document.getById(d).removeStyle("display"),POLARIS.document.getById(b).removeStyle("display"),POLARIS.document.getById(c).setStyle("display","none"))},h=function(a){return POLARIS.tools.getNextId()+"_"+a},g=h("pageNumberBothPreviewPanel"),c=h("pageNumberBothPreviewNumber"),k=h("pageNumberLeftPreviewPanel"),d=h("pageNumberLeftPreviewNumber"),
l=h("pageNumberRightPreviewPanel"),b=h("pageNumberRightPreviewNumber");return{title:e.pageNumber,minWidth:280,minHeight:40,resizable:POLARIS.DIALOG_RESIZE_NONE,contents:[{id:"info",elements:[{type:"vbox",children:[{type:"fieldset",label:e.pageNumberStyle.position,children:[]},{type:"hbox",id:"pageNumberPosition",children:[{type:"vbox",className:"page-no-position",children:[{id:"radioOptionBothTop",type:"radio",items:[["","1"],["","2"],["","3"]],onClick:f},{type:"html",html:'\x3cdiv id\x3d"'+g+'" style\x3d"border: 3px double #a0a2ab;width:73px;height:89px;display: table-cell;"\x3e\x3cspan id\x3d"'+
c+'"\x3e1\x3c/span\x3e\x3cdiv\x3e'},{id:"radioOptionBothBottom",type:"radio",items:[["","4"],["","5"],["","6"]],onClick:f}]},{type:"vbox",className:"page-no-position",children:[{id:"radioOptionInsideTop",type:"radio",items:[[e.pageNumberStyle.topInside,"7"]],onClick:f},{type:"html",html:'\x3cdiv id\x3d"'+k+'" style\x3d"border: 1px solid #a0a2ab;width:75px;height:91px;display: table-cell;"\x3e\x3cspan id\x3d"'+d+'"\x3e1\x3c/span\x3e\x3cdiv\x3e'},{id:"radioOptionInsideBottom",type:"radio",items:[[e.pageNumberStyle.bottomInside,
"8"]],onClick:f}]},{type:"vbox",className:"page-no-position",children:[{id:"radioOptionOutsideTop",type:"radio",items:[[e.pageNumberStyle.topOutside,"9"]],onClick:f},{type:"html",html:'\x3cdiv id\x3d"'+l+'" style\x3d"border: 1px solid #a0a2ab;width:75px;height:91px;display: table-cell;"\x3e\x3cspan id\x3d"'+b+'"\x3e1\x3c/span\x3e\x3cdiv\x3e'},{id:"radioOptionOutsideBottom",type:"radio",items:[[e.pageNumberStyle.bottomOutside,"10"]],onClick:f}]}]},{type:"vbox",className:"hbox_padding_zero",children:[{id:"radioOptionNone",
type:"radio",items:[[e.pageNumberStyle.none,"0"]],onClick:f}]},{type:"fieldset",label:e.pageNumberStyle.style,children:[]},{type:"hbox",id:"pageNumberStyle",verticalalign:"middle",widths:["50%","1px","auto"],children:[{type:"select",id:"pageNumberStyle","default":"1",items:[["1,2,3...","1"]]},{type:"html",html:""},{type:"checkbox",id:"pageNumberHypen",label:e.pageNumberStyle.hypen,onChange:function(){this.getValue()?(POLARIS.document.getById(d).setText("-1-"),POLARIS.document.getById(b).setText("-1-"),
POLARIS.document.getById(c).setText("-1-")):(POLARIS.document.getById(d).setText("1"),POLARIS.document.getById(b).setText("1"),POLARIS.document.getById(c).setText("1"))}}]},{type:"html",html:""}]}]}],onLoad:function(){m("0")},onShow:function(){"-1-"==POLARIS.document.getById(c).getText()&&this.getContentElement("info","pageNumberHypen").setValue(!0);var a=n.plugins.pagination.pageInfo;a.pageNumberPosition?("1"==a.pageNumberPosition?this.getContentElement("info","radioOptionBothTop").setValue("1"):
"2"==a.pageNumberPosition?this.getContentElement("info","radioOptionBothTop").setValue("2"):"3"==a.pageNumberPosition?this.getContentElement("info","radioOptionBothTop").setValue("3"):"4"==a.pageNumberPosition?this.getContentElement("info","radioOptionBothBottom").setValue("4"):"5"==a.pageNumberPosition?this.getContentElement("info","radioOptionBothBottom").setValue("5"):"6"==a.pageNumberPosition?this.getContentElement("info","radioOptionBothBottom").setValue("6"):"7"==a.pageNumberPosition?this.getContentElement("info",
"radioOptionInsideTop").setValue("7"):"8"==a.pageNumberPosition?this.getContentElement("info","radioOptionInsideBottom").setValue("8"):"9"==a.pageNumberPosition?this.getContentElement("info","radioOptionOutsideTop").setValue("9"):"10"==a.pageNumberPosition?this.getContentElement("info","radioOptionOutsideBottom").setValue("10"):this.getContentElement("info","radioOptionNone").setValue("0"),m(a.pageNumberPosition)):(this.getContentElement("info","radioOptionNone").setValue("0"),m("0"))},onOk:function(){function a(a){return'\x3cp width\x3d"100%"'+
(a?' style\x3d"'+a+'"':"")+"\x3e"+(d?"\x3cspan\x3e- \x3c/span\x3e":"")+'\x3cspan doc-data-role\x3d"page-number"\x3e\x26#8203;\x3c/span\x3e'+(d?"\x3cspan\x3e -\x3c/span\x3e":"")+"\x3c/p\x3e"}var c=this.pageNumberRadioSelected,d=this.getContentElement("info","pageNumberHypen").getValue(),b={header:{both:"",odd:"",even:""},footer:{both:"",odd:"",even:""},pageNumberPosition:c};switch(c){case "1":b.header.both=a("text-align:left;");break;case "2":b.header.both=a("text-align:center;");break;case "3":b.header.both=
a("text-align:right;");break;case "4":b.footer.both=a("text-align:left;");break;case "5":b.footer.both=a("text-align:center;");break;case "6":b.footer.both=a("text-align:right;");break;case "7":b.header.odd=a("text-align:right;");b.header.even=a("text-align:left;");break;case "8":b.footer.odd=a("text-align:right;");b.footer.even=a("text-align:left;");break;case "9":b.header.odd=a("text-align:left;");b.header.even=a("text-align:right;");break;case "10":b.footer.odd=a("text-align:left;"),b.footer.even=
a("text-align:right;")}n.fire("setPageNumber",b)}}})})();