(function(){POLARIS.dialog.add("pageoutline",function(h){function q(a,d,f){return function(){var b=this.getValue().trim(),b=!!(POLARIS.dialog.validate.number()(b)&&b>=d&&b<f+1);b||(alert(a),this.select());return b}}function p(){return function(){var a;a="1"==this.getDialog().getContentElement("info","radioOrientation").getValue()?parseFloat(this.getDialog().getContentElement("info","txtPaperWidth").getValue()):parseFloat(this.getDialog().getContentElement("info","txtPaperHeight").getValue());var d=
this.getValue().trim(),d=!!(POLARIS.dialog.validate.number()(d)&&0<=d&&d<a+1);if(!d)return alert(b.outline.invalidSize),this.select(),d;var d=parseFloat(this.getDialog().getContentElement("info","txtPaddingTop").getValue()),f=parseFloat(this.getDialog().getContentElement("info","txtPaddingBottom").getValue()),e=parseFloat(this.getDialog().getContentElement("info","txtHeaderHeight").getValue());if(0<e&&8>e){var c;c="\x3ctable\x3e\x3cthead\x3e\x3ctr\x3e";c+="\x3cth colspan\x3d3\x3e"+b.headerAndFooter.invalidHeaderHeight+
"\x3cbr\x3e\x3cbr\x3e\x3c/th\x3e";c+="\x3c/tr\x3e";c+="\x3c/thead\x3e";c+="\x3c/table\x3e";c=new POLARIS.plugins.notification(h,{message:c,type:"info",duration:3E3,width:300,valign:"top",align:"center"});c.show();e=8;this.getDialog().getContentElement("info","txtHeaderHeight").setValue(8)}c=parseFloat(this.getDialog().getContentElement("info","txtFooterHeight").getValue());0<c&&8>c&&(c="\x3ctable\x3e\x3cthead\x3e",c+="\x3ctr\x3e",c+="\x3cth colspan\x3d3\x3e"+b.headerAndFooter.invalidFooterHeight+
"\x3cbr\x3e\x3cbr\x3e\x3c/th\x3e",c+="\x3c/tr\x3e",c+="\x3c/thead\x3e",c+="\x3c/table\x3e",c=new POLARIS.plugins.notification(h,{message:c,type:"info",duration:3E3,width:300,valign:"top",align:"center"}),c.show(),c=8,this.getDialog().getContentElement("info","txtFooterHeight").setValue(8));NaN==d&&(d=0);NaN==f&&(f=0);NaN==e&&(e=0);NaN==c&&(c=0);(d=a>d+f+e+c)||alert(b.outline.invalidMargin);return d}}function r(){return function(){var a;a="1"==this.getDialog().getContentElement("info","radioOrientation").getValue()?
parseFloat(this.getDialog().getContentElement("info","txtPaperHeight").getValue()):parseFloat(this.getDialog().getContentElement("info","txtPaperWidth").getValue());var d=this.getValue().trim(),d=!!(POLARIS.dialog.validate.number()(d)&&0<=d&&d<a+1);if(!d)return alert(b.outline.invalidSize),this.select(),d;var d=parseFloat(this.getDialog().getContentElement("info","txtPaddingLeft").getValue()),f=parseFloat(this.getDialog().getContentElement("info","txtPaddingRight").getValue());NaN==d&&(d=0);NaN==
f&&(f=0);(d=a>d+f)||alert(b.outline.invalidMargin);return d}}var b=h.lang.pagination,m=function(a,d,f,e){this.isDefault=e;this.name=a;this.width=d;this.height=f;this.toString=function(){return a+" [ "+d+" x "+f+" "+b.outline.pageUnit+" ]"}},n={};n.B5=new m("B5",182,257);n.B4=new m("B4",257,364);n.A4=new m("A4",210,297,!0);n.A3=new m("A3",297,420);var m=function(a){return POLARIS.tools.getNextId()+"_"+a},t=m("previewPagePanel"),u=m("previewPageBodyPanel"),v=m("previewHeaderPanel"),w=m("previewFooterPanel"),
g=function(a){var d=a.getContentElement("info","txtPaperWidth").getValue(),b=a.getContentElement("info","txtPaperHeight").getValue();var d=parseInt(d),b=parseInt(b),e=70,c=100,l=1;0!=d&&0!=b&&NaN!=d&&NaN!=b&&(d>b?(e=90,c=Math.round(90*b/d),l=Math.round(d/90)):(e=Math.round(90*d/b),c=90,l=Math.round(b/90)));var k=POLARIS.document.getById(t);k&&(k.setStyle("width",e+"px"),k.setStyle("height",c+"px"));d=Math.round(a.getContentElement("info","txtPaddingLeft").getValue()/l);NaN==d&&(d=0,a.getContentElement("info",
"txtPaddingLeft").setValue("0"));k=Math.round(a.getContentElement("info","txtPaddingTop").getValue()/l);NaN==k&&(k=0);b=Math.round(a.getContentElement("info","txtPaddingRight").getValue()/l);NaN==b&&(b=0);var g=Math.round(a.getContentElement("info","txtPaddingBottom").getValue()/l);NaN==g&&(g=0);var h=Math.round(a.getContentElement("info","txtHeaderHeight").getValue()/l);NaN==h&&(h=0);a=Math.round(a.getContentElement("info","txtFooterHeight").getValue()/l);NaN==a&&(a=0);e=e-d-b;NaN==e&&(e=0);0>e&&
(e=0);c=c-k-g-h-a;NaN==c&&(c=0);0>c&&(c=0);if(l=POLARIS.document.getById(v))l.setStyle("width",e+"px"),l.setStyle("height",h+"px"),l.setStyle("margin-top",k+"px"),l.setStyle("margin-left",d+"px"),l.setStyle("margin-right",b+"px");if(k=POLARIS.document.getById(u))k.setStyle("width",e+"px"),k.setStyle("height",c+"px"),k.setStyle("margin-left",d+"px"),k.setStyle("margin-right",b+"px");if(c=POLARIS.document.getById(w))c.setStyle("width",e+"px"),c.setStyle("height",a+"px"),c.setStyle("margin-bottom",g+
"px"),c.setStyle("margin-left",d+"px"),c.setStyle("margin-right",b+"px")};return{title:b.outline.title,minWidth:537,minHeight:36,resizable:POLARIS.DIALOG_RESIZE_NONE,contents:[{id:"info",label:h.lang.common.generalTab,elements:[{type:"hbox",widths:["203px","1px","auto"],children:[{type:"html",html:"\x3cp\x3e"+b.outline.pageSize+"\x3c/p\x3e"},{type:"html",html:""},{type:"html",html:"\x3cp\x3e"+b.outline.margin+"\x3c/p\x3e"}]},{type:"hbox",widths:["203px","1px","auto"],children:[{type:"vbox",children:[{type:"select",
id:"paperType",items:[],setup:function(a){this.clear();a=a.size;var d=!1,f;for(f in n)this.add(n[f].toString(),f),f.toLowerCase()===a.toLowerCase()&&(this.setValue(f),d=!0);this.add(b.outline.userPageSize,"custom");d||this.setValue("custom")},onChange:function(){var a=this.getDialog().getContentElement("info","txtPaperWidth"),b=this.getDialog().getContentElement("info","txtPaperHeight");if(n[this.getValue()]){var f=n[this.getValue()],e="0"==this.getDialog().getContentElement("info","radioOrientation").getValue()?
"portrait":"landscape",c="portrait"===e?f.height:f.width;a.setValue("portrait"===e?f.width:f.height);b.setValue(c)}"custom"==this.getValue()?(a.getInputElement().removeAttribute("readOnly"),b.getInputElement().removeAttribute("readOnly"),a.focus()):(a.getInputElement().setAttribute("readOnly",!0),b.getInputElement().setAttribute("readOnly",!0))}},{type:"hbox",children:[{type:"hbox",widths:["66px","auto"],children:[{type:"text",id:"txtPaperWidth",validate:q(b.outline.invalidWidth,1,1E3),label:b.outline.width,
setup:function(a){this.setValue(parseFloat(a.width)+"")},onChange:function(){g(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit,style:"line-height: 32px;"}]}]},{type:"hbox",widths:["66px","auto"],children:[{type:"text",id:"txtPaperHeight",validate:q(b.outline.invalidHeight,1,1E3),label:b.outline.height,setup:function(a){this.setValue(parseFloat(a.height)+"")},onChange:function(){g(this.getDialog())}},{type:"vbox",children:[{type:"html",
html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit,style:"line-height: 32px;"}]}]}]},{type:"fieldset",label:b.outline.orientation,children:[]},{type:"html",html:""},{type:"radio",id:"radioOrientation","default":"0",items:[[b.outline.landscape,"1"],[b.outline.portrait,"0"]],setup:function(a){this.setValue("portrait"==a.orientation?"0":"1")},onChange:function(){var a=this.getDialog(),b=a.getContentElement("info","txtPaperWidth"),a=a.getContentElement("info","txtPaperHeight"),f=b.getValue(),e=a.getValue();
b.setValue(e);a.setValue(f)}}]},{type:"html",html:""},{type:"vbox",children:[{type:"vbox",className:"paper_margin_preview",textalign:"center",children:[{type:"hbox",verticalalign:"middle",textalign:"center",widths:["33%","33%","33%"],children:[{type:"html",html:""},{type:"hbox",widths:["66px","auto"],children:[{type:"text",id:"txtPaddingTop",className:"margin_input",validate:p(),label:b.outline.marginTop,setup:function(a){this.setValue(parseInt(a.marginTop)+"")},onKeyUp:function(){g(this.getDialog())},
onChange:function(){g(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit,style:"line-height: 32px;"}]}]},{type:"html",html:""}]},{type:"hbox",verticalalign:"middle",textalign:"center",widths:["33%","33%","33%"],children:[{type:"html",html:""},{type:"hbox",widths:["66px","auto"],children:[{type:"text",id:"txtHeaderHeight",className:"margin_input",validate:p(),label:b.outline.header,setup:function(a){this.setValue(parseInt(a.pageHeader.height)+
"")},onKeyUp:function(){g(this.getDialog())},onChange:function(){g(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit,style:"line-height: 32px;"}]}]},{type:"html",html:""}]},{type:"hbox",verticalalign:"middle",textalign:"center",widths:["33%","33%","33%"],children:[{type:"hbox",widths:["66px","auto"],children:[{type:"text",id:"txtPaddingLeft",className:"margin_input",validate:r(),label:b.outline.marginLeft,setup:function(a){this.setValue(parseInt(a.marginLeft)+
"")},onKeyUp:function(){g(this.getDialog())},onChange:function(){g(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit,style:"line-height: 32px;"}]}]},{type:"html",id:"pageOutlinePreview",html:'\x3cdiv style\x3d"border: 1px solid #a0a2ab;background-color:#fffeff;padding:0;width:100px;height:100px;line-height:100px;vertical-align:middle;text-align:center;overflow:hidden;"\x3e\x3cdiv id\x3d"'+t+'" style\x3d"border: 1px solid #a0a2ab;display:inline-block;overflow:hidden;"\x3e\x3cdiv id\x3d"'+
v+'" style\x3d"background-color:#d2d2d2;display:block;width:auto;height:auto"\x3e\x3c/div\x3e\x3cdiv id\x3d"'+u+'" style\x3d"background-color:#f5f5f5;display:block;width:auto;height:auto"\x3e\x3c/div\x3e\x3cdiv id\x3d"'+w+'" style\x3d"background-color:#d2d2d2;display:block;width:auto;height:auto"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e',setup:function(){}},{type:"hbox",widths:["66px","auto"],children:[{type:"text",id:"txtPaddingRight",className:"margin_input",validate:r(),label:b.outline.marginRight,
setup:function(a){this.setValue(parseInt(a.marginRight)+"")},onKeyUp:function(){g(this.getDialog())},onChange:function(){g(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit,style:"line-height: 32px;"}]}]}]},{type:"hbox",verticalalign:"middle",textalign:"center",widths:["33%","33%","33%"],children:[{type:"html",html:""},{type:"hbox",widths:["66px","auto"],children:[{type:"text",id:"txtFooterHeight",className:"margin_input",validate:p(),label:b.outline.footer,
setup:function(a){this.setValue(parseInt(a.pageFooter.height)+"")},onKeyUp:function(){g(this.getDialog())},onChange:function(){g(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit,style:"line-height: 32px;"}]}]},{type:"html",html:""}]},{type:"hbox",verticalalign:"middle",textalign:"center",widths:["33%","33%","33%"],children:[{type:"html",html:""},{type:"hbox",widths:["66px","auto"],children:[{type:"text",id:"txtPaddingBottom",className:"margin_input",
validate:p(),label:b.outline.marginBottom,setup:function(a){this.setValue(parseInt(a.marginBottom)+"")},onKeyUp:function(){g(this.getDialog())},onChange:function(){g(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit,style:"line-height: 32px;"}]}]},{type:"html",html:""}]}]},{type:"html",html:""}]}]}]}],onLoad:function(){},onShow:function(){this.setupContent(h.plugins.pagination.pageInfo)},onOk:function(){var a=h.plugins.pagination.pageInfo,
d=this.getContentElement("info","paperType").getValue(),f="0"==this.getContentElement("info","radioOrientation").getValue()?"portrait":"landscape",e=this.getContentElement("info","txtPaperWidth").getValue()+b.outline.pageUnit,c=this.getContentElement("info","txtPaperHeight").getValue()+b.outline.pageUnit,g=this.getContentElement("info","txtPaddingLeft").getValue()+b.outline.pageUnit,k=this.getContentElement("info","txtPaddingRight").getValue()+b.outline.pageUnit,m=this.getContentElement("info","txtPaddingTop").getValue()+
b.outline.pageUnit,n=this.getContentElement("info","txtPaddingBottom").getValue()+b.outline.pageUnit,p=this.getContentElement("info","txtHeaderHeight").getValue()+b.outline.pageUnit,q=this.getContentElement("info","txtFooterHeight").getValue()+b.outline.pageUnit;a.size="custom"===d?"":d;a.border=!1;a.orientation=f;a.width=e;a.height=c;a.marginLeft=g;a.marginRight=k;a.marginTop=m;a.marginBottom=n;a.pageHeader.height=p;a.pageFooter.height=q;h.plugins.pagination.updatePageStyle(h);h.fire("zoom",{type:h.ui.zoomType,
ratio:h.ui.zoomRatio,updateScrollbarVisibility:1})}}})})();