POLARIS.dialog.add("scaytDialog",function(b){var k=b.scayt;k.getLogo();k.getLocal("version");k.getVersion();k.getLocal("text_copyrights");var l={isChanged:function(){return null===this.newLang||this.currentLang===this.newLang?!1:!0},currentLang:k.getLang(),newLang:null,reset:function(){this.currentLang=k.getLang();this.newLang=null},id:"lang"},n=[{id:"options",label:k.getLocal("tab_options"),onShow:function(){},elements:[{type:"vbox",id:"scaytOptions",children:function(){var a=k.getApplicationConfig(),
e=[],c={"ignore-all-caps-words":b.lang.scayt.label_allCaps,"ignore-domain-names":b.lang.scayt.label_ignoreDomainNames,"ignore-words-with-mixed-cases":b.lang.scayt.label_mixedCase,"ignore-words-with-numbers":b.lang.scayt.label_mixedWithDigits},d;for(d in a)a={type:"checkbox"},a.id=d,a.label=c[d],e.push(a);return e}(),onShow:function(){this.getChild();for(var a=b.scayt,e=0;e<this.getChild().length;e++)this.getChild()[e].setValue(a.getApplicationConfig()[this.getChild()[e].id])}}]}];b.on("scaytUserDictionaryAction",
function(a){var e=SCAYT.prototype.UILib,c=a.data.dialog,d=c.getContentElement("dictionaries","dictionaryNote").getElement(),f=a.editor.scayt,b;void 0===a.data.error?(b=f.getLocal("message_success_"+a.data.command+"Dic"),b=b.replace("%s",a.data.name),d.setText(b),e.css(d.$,{color:"blue"})):(""===a.data.name?d.setText(f.getLocal("message_info_emptyDic")):(b=f.getLocal("message_error_"+a.data.command+"Dic"),b=b.replace("%s",a.data.name),d.setText(b)),e.css(d.$,{color:"red"}),null!=f.getUserDictionaryName()&&
""!=f.getUserDictionaryName()?c.getContentElement("dictionaries","dictionaryName").setValue(f.getUserDictionaryName()):c.getContentElement("dictionaries","dictionaryName").setValue(""))});b.on("scaytUserDictionaryActionError",function(a){var e=SCAYT.prototype.UILib,c=a.data.dialog,d=c.getContentElement("dictionaries","dictionaryNote").getElement(),b=a.editor.scayt,h;""===a.data.name?d.setText(b.getLocal("message_info_emptyDic")):(h=b.getLocal("message_error_"+a.data.command+"Dic"),h=h.replace("%s",
a.data.name),d.setText(h));e.css(d.$,{color:"red"});null!=b.getUserDictionaryName()&&""!=b.getUserDictionaryName()?c.getContentElement("dictionaries","dictionaryName").setValue(b.getUserDictionaryName()):c.getContentElement("dictionaries","dictionaryName").setValue("")});var m={title:b.lang.scayt.text_title,resizable:POLARIS.DIALOG_RESIZE_NONE,minWidth:254,minHeight:80,onLoad:function(){if(0!=b.config.scayt_uiTabs[1]){var a=m,e=a.getLangBoxes.call(this);e.getParent().setStyle("white-space","normal");
a.renderLangList(e);this.definition.minWidth=this.getSize().width;this.resize(this.definition.minWidth,this.definition.minHeight)}},onCancel:function(){l.reset()},onHide:function(){b.unlockSelection()},onShow:function(){b.fire("scaytDialogShown",this);if(0!=b.config.scayt_uiTabs[2]){var a=b.scayt,e=this.getContentElement("dictionaries","dictionaryName"),c=this.getContentElement("dictionaries","existDic").getElement().getParent(),d=this.getContentElement("dictionaries","notExistDic").getElement().getParent();
c.hide();d.hide();null!=a.getUserDictionaryName()&&""!=a.getUserDictionaryName()?(this.getContentElement("dictionaries","dictionaryName").setValue(a.getUserDictionaryName()),c.show()):(e.setValue(""),d.show())}},onOk:function(){var a=m,e=b.scayt;this.getContentElement("options","scaytOptions");a=a.getChangedOption.call(this);e.commitOption({changedOptions:a})},toggleDictionaryButtons:function(a){var b=this.getContentElement("dictionaries","existDic").getElement().getParent(),c=this.getContentElement("dictionaries",
"notExistDic").getElement().getParent();a?(b.show(),c.hide()):(b.hide(),c.show())},getChangedOption:function(){var a={};if(1==b.config.scayt_uiTabs[0])for(var e=this.getContentElement("options","scaytOptions").getChild(),c=0;c<e.length;c++)e[c].isChanged()&&(a[e[c].id]=e[c].getValue());l.isChanged()&&(a[l.id]=b.config.scayt_sLang=l.currentLang=l.newLang);return a},buildRadioInputs:function(a,e){var c=new POLARIS.dom.element("div");POLARIS.document.createElement("div");var d="scaytLang_"+e,f=POLARIS.dom.element.createFromHtml('\x3cinput id\x3d"'+
d+'" type\x3d"radio"  value\x3d"'+e+'" name\x3d"scayt_lang" /\x3e'),h=new POLARIS.dom.element("label"),g=b.scayt;c.setStyles({"white-space":"normal",position:"relative","padding-bottom":"2px"});f.on("click",function(a){l.newLang=a.sender.getValue()});h.appendText(a);h.setAttribute("for",d);c.append(f);c.append(h);e===g.getLang()&&(f.setAttribute("checked",!0),f.setAttribute("defaultChecked","defaultChecked"));return c},renderLangList:function(a){var e=a.find("#left-col-"+b.name).getItem(0);a=a.find("#right-col-"+
b.name).getItem(0);var c=k.getLangList(),d={},f=[],h=0,g;for(g in c.ltr)d[g]=c.ltr[g];for(g in c.rtl)d[g]=c.rtl[g];for(g in d)f.push([g,d[g]]);f.sort(function(a,b){var c=0;a[1]>b[1]?c=1:a[1]<b[1]&&(c=-1);return c});d={};for(c=0;c<f.length;c++)d[f[c][0]]=f[c][1];f=Math.round(f.length/2);for(g in d)h++,this.buildRadioInputs(d[g],g).appendTo(h<=f?e:a)},getLangBoxes:function(){return this.getContentElement("langs","langBox").getElement()},contents:function(a,b){var c=[],d=b.config.scayt_uiTabs;if(d)for(var f in d)1==
d[f]&&c.push(a[f]);else return a;return c}(n,b)};return m});