POLARIS.editorConfig=function(a){a.customer="CLOUD ONNARA";a.height="500px";a.width="850px";a.paddingleft="18px";a.paddingright="18px";a.paddingtop="18px";a.scrollWidth="20px";a.userMode="user";a.wordprocessor=!0;a.showRuler=!1;a.fileUploadMaxFileSize=20971520;a.fontSize_sizes="8/8pt;9/9pt;10/10pt;11/11pt;12/12pt;13/13pt;14/14pt;15/15pt;16/16pt;17/17pt;18/18pt;19/19pt;20/20pt;22/22pt;24/24pt;26/26pt;28/28pt;36/36pt;48/48pt;72/72pt";a.documentFontFamily="돋움체";a.documentFontSize="12";a.documentLineHeight=
"1.6";a.tableLineHeight="1.3";a.filebrowserUploadUrl="";a.filebrowserImageUploadUrl="";a.tabSpaces=4;a.docConvertingUrl="";a.docConvertShareStoragePath="";a.docConvertImageContextPath="";a.useDocConvertServer=!0;a.useImageBase64Encoding=!1;a.undoStackSize=1E3;a.externalVideoLinkUrl="";a.externalDocumentLinkUrl="";a.pageBgColor="#f5f5f5";a.pageBorderColor="#d2d2d2";a.pageMarginLeft="20mm";a.pageMarginTop="10mm";a.pageMarginRight="20mm";a.pageMarginBottom="10mm";a.pageHeaderHeight="15mm";a.pageFooterHeight=
"15mm";a.exportHTML=!0;a.onPrintClick=null;a.defaultAdjustImageSize=200;a.blockPaste=!1;a.removeParagraphNumber=!1;a.enableTabKeyTools=!1;a.showFieldName=!0;a.showFontChangeNoti=!0;a.dialog_noConfirmCancel=!0;a.clickHereConvert=!1;a.autogrow=!1;a.showClickHere=!1;a.showLoadingSpinner=!0;a.showTableBorder=!1;a.font_names="돋움체/돋움체, DotumChe;바탕체/바탕체, BatangChe;굴림체/굴림체, GulimChe;궁서체/궁서체, GungsuhChe;휴먼명조/휴먼명조;나눔고딕코딩/나눔고딕코딩;HY견고딕/HY견고딕, 돋움체, DotumChe;HY헤드라인M/HY헤드라인M;Arial/Arial, Helvetica, 바탕체, sans-serif;Georgia/Georgia, 바탕체, serif;Times New Roman/Times New Roman, Times, 바탕체, serif;Verdana/Verdana, Geneva, 바탕체, sans-serif;";
a.font_replacement={"돋움":"돋움체",dotum:"돋움체","바탕":"바탕체",batang:"바탕체","굴림":"굴림체",gulim:"굴림체","궁서":"궁서체",gungsuh:"궁서체"};a.toolbarMode=1;a.toolbar=[{name:"TOOLBAR_STANDARD",show:!0,items:"Print - Undo Redo - Cut Copy Paste - TextColor BGColor - PageOutline HeaderFooter - Outdent Indent AutoOutdent - ZoomCombo - Find Replace".split(" ")},"/",{name:"TOOLBAR_FORMAT",show:!0,items:"Font FontSize Bold Italic Underline Strike - FontShape ParagraphForm - JustifyLeft JustifyCenter JustifyRight JustifyBlock - lineheight letter-spacing - Image Table SpecialChar".split(" ")},
"/"];a.quickaccesstoolbar=[{name:"row1",items:"Undo Redo - Font FontSize - Bold Italic Underline Strike - FontShape ParagraphForm - JustifyLeft JustifyCenter JustifyRight JustifyBlock - lineheight letter-spacing - Image Table SpecialChar".split(" ")},"/"];a.menubar=[{name:"label_file",items:[{name:"Templates"},{name:"DocumentInfo"},{name:"-"},{name:"-"},{name:"Print"},{name:"ExportPDF"},{name:"ExportHTML"}]},{name:"label_edit",items:[{name:"Undo"},{name:"Redo"},{name:"-"},{name:"Cut"},{name:"Copy"},
{name:"Paste"},{name:"label_selectAndPaste",items:[{name:"PasteText"},{name:"PasteFromWord"}]},{name:"Delete"},{name:"SelectAll"},{name:"-"},{name:"Find"},{name:"Replace"},{name:"Movement"},{name:"label_changeCase",items:[{name:"ChangeCase"},{name:"ChangeCharWidth"}]},{name:"Edit"}]},{name:"label_view",items:[{name:"Zoom"},{name:"ShowTableBorder"},{name:"ShowImageBorder"},{name:"-"},{name:"label_grid",items:[{name:"Grid"},{name:"GridLineSet"}]},{name:"-"},{name:"TogglePageOutline"},{name:"Ruler"}]},
{name:"label_input",items:[{name:"SpecialChar"},{name:"-"},{name:"label_dateTime",items:[{name:"InsertTime"},{name:"InsertTimeFormat"}]},{name:"label_comment",items:[{name:"FootNote"},{name:"EndNote"},{name:"FootEndNoteStyle"},{name:"FootEndNoteSave"},{name:"FootEndNoteChange"}]},{name:"-"},{name:"label_object",items:[{name:"Image"},{name:"TextBox"},{name:"ParagraphLine"}]},{name:"-"},{name:"Anchor"},{name:"Link"},{name:"ClickHere"},{name:"-"},{name:"InsertExternalVideoUrl"},{name:"InsertExternalDocumentUrl"}]},
{name:"label_design",items:[{name:"FontShape"},{name:"ParagraphForm"},{name:"label_numberedList",items:[{name:"NumberedParagraphFormat"},{name:"NumberedList"},{name:"BulletedList"},{name:"Outdent"},{name:"Indent"}]},{name:"-"},{name:"PageOutline"},{name:"-"},{name:"HeaderFooter"},{name:"PageBorderStyle"},{name:"PageNumber"},{name:"-"},{name:"BreakPage"}]},{name:"label_tool",items:[{name:"label_blockCalc",items:[{name:"BlockCalcSum"},{name:"BlockCalcAvg"}]}]},{name:"label_table",items:[{name:"Table"},
{name:"-"},{name:"TableProperties"},{name:"CellProperties"},{name:"label_cellBg",items:[{name:"ApplyForEachCell"},{name:"ApplyAsSingleCell"}]},{name:"SameHeight"},{name:"SameWidth"},{name:"-"},{name:"CellSplit"},{name:"CellMerge"},{name:"CellMergeCancel"},{name:"label_cellInsert",items:[{name:"RowInsertBefore"},{name:"RowInsertAfter"},{name:"ColumnInsertBefore"},{name:"ColumnInsertAfter"}]},{name:"label_cellDelete",items:[{name:"RowDelete"},{name:"ColumnDelete"}]},{name:"-"},{name:"label_verticalAlign",
items:[{name:"VerticalAlignTop"},{name:"VerticalAlignMiddle"},{name:"VerticalAlignBottom"}]},{name:"-"},{name:"label_cellBlockCalc",items:[{name:"CellBlockSum"},{name:"CellBlockAverage"},{name:"CellBlockMultiply"}]},{name:"label_cellSimpleCalc",items:[{name:"TableSumRow"},{name:"TableSumColumn"},{name:"TableAverageRow"},{name:"TableAverageColumn"},{name:"TableMultiplyRow"},{name:"TableMultiplyColumn"}]},{name:"label_thousandanize",items:[{name:"TableAddComma"},{name:"TableRemoveComma"}]}]},{name:"label_help",
items:[{name:"UserManual"},{name:"ShortcutManual"},{name:"TableManual"},{name:"Restriction"}]}];a.ribbonbar=[{name:"label_edit",groups:[{tools:[{name:"Cut",showLabel:"bottom"},{name:"Copy",showLabel:"bottom"},{name:"PasteOption",showLabel:"bottom"}]},{tools:[{name:"FontShape",showLabel:"bottom"},{name:"ParagraphForm",showLabel:"bottom"},{name:"Edit",showLabel:"bottom"}]},{tools:[{name:"Image",showLabel:"bottom"},{name:"SpecialChar",showLabel:"bottom"},{name:"Table",showLabel:"bottom"}]},{tools:[{name:"Find",
showLabel:"bottom"},{name:"Movement",showLabel:"bottom"},{name:"Replace",showLabel:"bottom"}]},{tools:[{name:"SelectAll",showLabel:"bottom"}]}]},{name:"label_input",groups:[{tools:[{name:"SpecialChar",showLabel:"bottom"}]},{tools:[{name:"Table",showLabel:"bottom"}]},{tools:[{name:"Date",showLabel:"bottom"},{name:"Comment",showLabel:"bottom"}]},{tools:[{name:"Image",showLabel:"bottom"},{name:"TextBox",showLabel:"bottom"},{name:"ParagraphLine",showLabel:"bottom"}]},{tools:[{name:"Anchor",showLabel:"bottom"},
{name:"Link",showLabel:"bottom"}]}]},{name:"label_design",groups:[{tools:[{name:"FontShape",showLabel:"bottom"},{name:"ParagraphForm",showLabel:"bottom"}]},{tools:[{name:"NumberedParagraphFormat",showLabel:"bottom"},{name:"NumberedList",showLabel:"bottom"},{name:"BulletedList",showLabel:"bottom"}]},{tools:[{name:"Outdent",showLabel:"bottom"},{name:"Indent",showLabel:"bottom"},{name:"AutoOutdent",showLabel:"bottom"}]},{tools:[{name:"HeaderFooter",showLabel:"bottom"},{name:"PageOutline",showLabel:"bottom"},
{name:"PageNumber",showLabel:"bottom"}]},{tools:[{name:"BreakPage",showLabel:"bottom"}]},{tools:[{name:"ChangeCase",showLabel:"bottom"},{name:"ChangeCharWidth",showLabel:"bottom"}]}]},{name:"label_view",groups:[{tools:[{name:"Zoom",showLabel:"bottom"}]},{tools:[{name:"ShowTableBorder",showLabel:"bottom"},{name:"ShowImageBorder",showLabel:"bottom"}]},{tools:[{name:"Grid",showLabel:"bottom"},{name:"GridLineSet",showLabel:"bottom"}]},{tools:[{name:"TogglePageOutline",showLabel:"bottom"}]}]},{name:"label_table",
groups:[{tools:[{name:"Table",showLabel:"bottom"}]},{tools:[{name:"TableProperties",showLabel:"bottom"},{name:"CellProperties",showLabel:"bottom"},{name:"CellBorder",showLabel:"bottom"},{name:"SameHeight",showLabel:"bottom"},{name:"SameWidth",showLabel:"bottom"}]},{tools:[{name:"CellSplit",showLabel:"bottom"},{name:"CellMerge",showLabel:"bottom"},{name:"CellMergeCancel",showLabel:"bottom"},{name:"CellInsert",showLabel:"bottom"},{name:"CellDelete",showLabel:"bottom"}]},{tools:[{name:"VerticalAlign",
showLabel:"bottom"}]},{tools:[{name:"BlockCalc",showLabel:"bottom"},{name:"SimpleCalc",showLabel:"bottom"},{name:"Thousandanize",showLabel:"bottom"}]}]}]};